default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: heroku-partner-app-social_development

development_heroku_connect:
  <<: *default
  database: heroku-partner-app-social_heroku_connect_development

test:
  <<: *default
  database: heroku-partner-app-social_test

test_heroku_connect:
  <<: *default
  database: heroku-partner-app-social_heroku_connect_test
