development:
  app_id: "1554382644803582"
  secret_key: "c90dfb96b0ca39dcbaf28bc63ce37a9a"
  site_url: "https://graph.facebook.com/v2.3/"
  token_url: "/oauth/access_token"
  authorize_url: "https://www.facebook.com/dialog/oauth?client_id=%s&redirect_uri=%s"
  callback_url: "http://localhost:3000/sessions/facebook/callback"
